name: course-webscraping
channels:
  - anaconda
  - defaults
dependencies:
  - beautifulsoup4=4.9.1
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - idna=2.9
  - libedit=3.1.20181209
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1g
  - pip=20.0.2
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.7.6
  - readline=8.0
  - requests=2.23.0
  - setuptools=47.1.1
  - six=1.15.0
  - soupsieve=2.0.1
  - sqlite=3.31.1
  - tk=8.6.8
  - urllib3=1.25.8
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
